# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.srcs/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/zb_blinky_block3_PmodCMPS2_0_1.xci
# IP: The module: 'zb_blinky_block3_PmodCMPS2_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_axi_iic_0_0 || ORIG_REF_NAME==PmodCMPS2_axi_iic_0_0} -quiet] -quiet

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/PmodCMPS2_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCMPS2_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_xlconstant_0_0/PmodCMPS2_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_xlconstant_0_0 || ORIG_REF_NAME==PmodCMPS2_xlconstant_0_0} -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCMPS2_axi_iic_0_0 || ORIG_REF_NAME==PmodCMPS2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0_ooc.xdc

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/zb_blinky_block3_PmodCMPS2_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_PmodCMPS2_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_PmodCMPS2_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/PmodCMPS2_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCMPS2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCMPS2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.srcs/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/zb_blinky_block3_PmodCMPS2_0_1.xci
# IP: The module: 'zb_blinky_block3_PmodCMPS2_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_axi_iic_0_0 || ORIG_REF_NAME==PmodCMPS2_axi_iic_0_0} -quiet] -quiet

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/PmodCMPS2_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCMPS2_pmod_bridge_0_0} -quiet] -quiet

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_xlconstant_0_0/PmodCMPS2_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodCMPS2_xlconstant_0_0 || ORIG_REF_NAME==PmodCMPS2_xlconstant_0_0} -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCMPS2_axi_iic_0_0 || ORIG_REF_NAME==PmodCMPS2_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_axi_iic_0_0/PmodCMPS2_axi_iic_0_0_ooc.xdc

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/zb_blinky_block3_PmodCMPS2_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_PmodCMPS2_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_PmodCMPS2_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/PmodCMPS2_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodCMPS2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodCMPS2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/src/PmodCMPS2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
