# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/srcs/top.xdc

# Block Designs: bd/zb_blinky_block3/zb_blinky_block3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3 || ORIG_REF_NAME==zb_blinky_block3} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_processing_system7_0_0/zb_blinky_block3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_processing_system7_0_0 || ORIG_REF_NAME==zb_blinky_block3_processing_system7_0_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_zedboard_blinky_test_0_0/zb_blinky_block3_zedboard_blinky_test_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_zedboard_blinky_test_0_0 || ORIG_REF_NAME==zb_blinky_block3_zedboard_blinky_test_0_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_PmodESP32_0_0/zb_blinky_block3_PmodESP32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_PmodESP32_0_0 || ORIG_REF_NAME==zb_blinky_block3_PmodESP32_0_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_axi_gpio_0_0/zb_blinky_block3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_axi_gpio_0_0 || ORIG_REF_NAME==zb_blinky_block3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_axi_smc_0/zb_blinky_block3_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_axi_smc_0 || ORIG_REF_NAME==zb_blinky_block3_axi_smc_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_rst_ps7_0_100M_0/zb_blinky_block3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_rst_ps7_0_100M_0 || ORIG_REF_NAME==zb_blinky_block3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zb_blinky_block3/ip/zb_blinky_block3_PmodCMPS2_0_1/zb_blinky_block3_PmodCMPS2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zb_blinky_block3_PmodCMPS2_0_1 || ORIG_REF_NAME==zb_blinky_block3_PmodCMPS2_0_1} -quiet] -quiet

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/zb_blinky_block3_ooc.xdc
