# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.srcs/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_processing_system7_0_0/zb_blinky_block3_processing_system7_0_0.xci
# IP: The module: 'zb_blinky_block3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_processing_system7_0_0/zb_blinky_block3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.srcs/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_processing_system7_0_0/zb_blinky_block3_processing_system7_0_0.xci
# IP: The module: 'zb_blinky_block3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jkelley/Documents/Xilinx/zedboard_blinky_test_step3/hardware/zedboard_blinky_test_step3.gen/sources_1/bd/zb_blinky_block3/ip/zb_blinky_block3_processing_system7_0_0/zb_blinky_block3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_blinky_block3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
